### ISSUE TITLE
Allow uninducted members to be given accounts

### ISSUE THREAD

**Issue by bnjns** [backstage-technical-services/hub#108]
In GitLab by @ACascarino on Oct 27, 2019, 10:34

#### Request

Currently, our internal policy is to only add members to the website when they have both a) paid membership and b) attended induction. This makes keeping track of late joining members difficult, and creates a strange middle ground for members who have bought membership but have not done an induction - we tend to then run an induction for them on-event, but having then sign up to an event without website access is tricky!

Further, this restriction on having members only added to the website once they've been inducted makes the induction skill fairly redundant and an administrative faff.

A proposed solution would be a simple visual indicator, visible to committee and the TEM, on members who sign up to an event without having level 2, in combination with an email alert warning the committee and the TEM that this member would need an induction before they can crew the event.

This provides a nice middle ground, allowing paid members to have website access, making it more obvious for TEMs and committee that certain members require an induction, and gives the induction skill a purpose.

#### Where should this go?

Events diary! And a small crossover with the skills section

#### Rationale

Mostly explained above I guess

#### Urgency

Realistically too late to be useful this year, so in place by next academic year would be the deadline

**Comment by ACascarino** [comment]
Just to chime in here whilst I remember - I believe the committee then later voted to reverse that decision and give uninducted members accounts... might be worth confirming and adding as a feature either to the current website if desired or to the new SPA

**Comment by bnjns** [comment]
Ooh, did they? Would you be able to open a new issue if they okayed it (just so not everything is written by me :joy: )?

We can definitely include this in the scope of the API/SPA.

**Comment by ACascarino** [comment]
They did! Opening a new issue now :)
