### ISSUE TITLE
Error in setting committee from election results

### ISSUE THREAD

**Issue by Hypothawits** [backstage-technical-services/hub#122]
#### Summary

Gives "unknown error" message when using saving after set committee button on election page.
Work around is to set committee from membership list

#### Actual behaviour
![image](https://user-images.githubusercontent.com/18664612/88983024-acedad00-d2c1-11ea-9b22-380a3334b366.png)

#### Expected behaviour

give the members committee privileges 

#### Steps to reproduce
open committee election, set committee, select members to set as committee, hit save. 

#### When did it happen?

12:05AM 31 July 2020

#### Urgency
Low

**Comment by Hypothawits** [comment]
I think also that setting the committee also sets it as the result for that election? so that's also not working

**Comment by bnjns** [comment]
The workaround will only work for setting permissions etc, not for saving the results of the election :confused: 

Can you open the network tab, try again and post a screenshot of the error message you get back? I couldn't find any helpful logs.

**Comment by Hypothawits** [comment]
Is this the network tab? seems to say it's a 404
![image](https://user-images.githubusercontent.com/18664612/88984016-6baacc80-d2c4-11ea-88c7-401367e101f8.png)

**Comment by bnjns** [comment]
Ah, I've spotted it - there's `//` in the URL. It should be `https://www.bts-crew.com/elections/22/elect`. I suspect this is the same bug that we noticed before.

From a quick glance, I think this is the problematic line: https://github.com/backstage-technical-services/laravel-site/blob/master/resources/views/elections/modals/elect.blade.php#L34. I think it should be

```
                data-form-action="{{ route('election.elect', ['id' => $election->id]) }}"
```

**Comment by Hypothawits** [comment]
ah nice find! yes I remember that from the manifesto issue!
