### ISSUE TITLE
Issue changing profile picture

### ISSUE THREAD

**Issue by betts-jt** [backstage-technical-services/hub#123]
#### Summary
I'm not sure if this is a known issue but couldn't see it when looking through the issues list. 

I am unable to change my profile picture on the website. When I select a file and click the 'change picture' button I get the message profile picture changed at the bottom of the page but the profile picture stays the same. 

Additionally to this if I remove my profile picture, which works correctly, and then try and upload a new image the image reverts back to my original profile picture and not the new image file I have selected. 

Not sure if this should be 2 issues.

#### Actual behaviour

What is happening that you think shouldn't happen?

When I click the change picture button when trying to change my profile picture I get the profile picture changed box but the image is the same as before. 

When uploading a new profile picture, after removing my old one, the profile picture reverts back to the original removed image, not the new one.

#### Expected behavior

Change my profile picture to the selected image file.

#### Steps to reproduce

Attempt to change profile picture on the website.

#### When did it happen?

Just before 1300 on Friday the 31st of July.

#### Urgency

How quickly does this need to be resolved? Is this preventing you or anyone else from being able to do something you/they need to?

Low

**Comment by ACascarino** [comment]
You mean you in a snazzy Christmas tree hat *isn't* a great first impression of you as chair?

**Comment by betts-jt** [comment]
Not exactly... This appears to work now having changed to a different computer so think it was my ageing laptop acting odd. My apologies

**Comment by bnjns** [comment]
That was easy :joy:
