### ISSUE TITLE
Skill revoking not working

### ISSUE THREAD

**Issue by olieolieolieoli** [backstage-technical-services/hub#131]
#### Summary

Can't fully revoke any skills

#### Actual behaviour

Error message - 'please select a valid level'

![image](https://user-images.githubusercontent.com/83349452/116402450-5e574a00-a824-11eb-8223-0d9f83ef9711.png)

#### Expected behaviour

Revoke skill

#### Steps to reproduce

bts/training/skills/[insert skill number] -> revoke

#### When did it happen?

13:15 (ish), 28/04/21

#### Urgency

High - prevents revoking of expired safety critical skills

**Comment by bnjns** [comment]
We need way more information - what skill are you trying to revoke and from whom? What level are you revoking to? We can't replicate if we don't have the exact steps.

The screenshot is also super blurry so I can't see much but it looks like you don't have the member dropdown in that form, so I would wager you're blocking JS?

**Comment by olieolieolieoli** [comment]
Sorry - Tried it with multiple skills, can't revoke from any level to nothing for any member. This one was for Cara Phillips from L2 in Event Manager - culturals to no skill

**Comment by bnjns** [comment]
@olieolieolieoli Is this still an issue? Are you able to check this:

> The screenshot is also super blurry so I can't see much but it looks like you don't have the member dropdown in that form, so I would wager you're blocking JS?

Otherwise I'll close this off :slightly_smiling_face:
