### ISSUE TITLE
Website links to GitLab

### ISSUE THREAD

**Issue by olieolieolieoli** [backstage-technical-services/hub#133]
#### Summary

Website button still links to GitLab

#### Actual behaviour

Sent to GitLab not Git Hub

#### Expected behaviour

Send me to the right website

#### Steps to reproduce

Click button on footer of website -> sent to GitLab (error 404 - page not found)

#### When did it happen?

13:29, 28/4/21

#### Urgency

High - couldn't report website issues

**Comment by bnjns** [comment]
Fixed in https://github.com/backstage-technical-services/laravel-site/commit/f41866b3cb7b3450332adfc7ec2a791edab898b4
