### ISSUE TITLE
AJAX calls are often retried, which often results in "undoing" the intended change

### ISSUE THREAD

**Issue by TeefaAly** [backstage-technical-services/hub#135]
#### Summary

When pressing the "Volunteer" button, people are not being assigned to the event but still receive emails saying they have volunteered. 

#### Actual behaviour

When pressing the volunteer button on events, it should assign you to the event and list you under "General Crew" but thats not happening. Instead when pressing the volunteer button you get sent an email saying you volunteered for the event but on the website your name doesnt appear under the general crew list.

#### Expected behaviour

Assign you as general crew on the website

#### Steps to reproduce

Pressing the volunteer button for an event.

#### When did it happen?

Started noticing this bug beginning of February 2022. 

#### Urgency

High urgency. Mainly an issue for training events, but also an issue when signing up for regular events as general crew.

-Mostafa Aly

**Comment by bnjns** [comment]
I've been able to reproduce this locally. It looks like it volunteers you and then immediately unvolunteers you :thinking:

**Comment by bnjns** [comment]
This has been confirmed to also affect approving awards (#137).

**Comment by bnjns** [comment]
So I may have found the issue - @TeefaAly @nbibaud @alexbabington would you be able to check and confirm whether your reported issues are fixed?
