### ISSUE TITLE
When attempting to set profile picture an error is returned 

### ISSUE THREAD

**Issue by matt01** [backstage-technical-services/hub#140]
When attempting to set a profile picture, on the staging.bts-crew.com, site the following is shown:

![image](https://github.com/user-attachments/assets/3ae19532-f47a-4c35-bf05-03be2359a3ff)

The return code is 500 and the following is sent back:

```
{
    "message": "Server Error"
}
```

**Comment by bnjns** [comment]
Thanks for reporting - looks like we don't have GD properly installed (which is what we use for image manipulation). I'll take a look at fixing later today.

```
Call to undefined function Intervention\\Image\\Gd\\imagejpeg()
```

**Comment by bnjns** [comment]
This should be fixed in the latest build on staging
